#!/bin/bash

echo

current_date=$(date)

hostname=$(hostname)
distro=$(lsb_release -d | cut -f2)
uptime=$(uptime -p)

cpu=$(lscpu | grep "Model name" | cut -d: -f2 | sed 's/^[ \t]*//')
ram=$(free -h | grep Mem | awk '{print $2}')

disk_info=""
for disk in $(lsblk -d -o NAME | grep -E '^sd|^nvme|^mmcblk|^sr'); do
    size=$(lsblk /dev/$disk -o SIZE -n)
    model=$(sudo lshw -class disk -short | grep "/dev/$disk" | awk '{print $2, $3}')
    if [[ -n "$model" ]]; then
        disk_info+="$disk ($model) $size"$'\n'
    fi
done

fqdn=$(hostname -f)
ip_address=$(ip a | grep inet | grep -v inet6 | awk '{print $2}' | cut -d/ -f1 | head -n 1)
gateway_ip=$(ip r | grep default | awk '{print $3}')
dns_server=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}')

users_logged_in=$(who | awk '{print $1}' | sort | uniq | paste -sd, -)
disk_space=$(df -h --output=source,avail | grep '^/' | awk '{print $1 " " $2}')
process_count=$(ps aux --no-headers | wc -l)
load_averages=$(uptime | awk -F'load average:' '{print $2}' | sed 's/^ *//')

ufw_status=$(sudo ufw status | grep Status | awk '{print $2}')

cat << EOF

System Report generated by $USER, $current_date

System Information
------------------
Hostname: $hostname
OS: $distro
Uptime: $uptime

Hardware Information
--------------------
cpu: $cpu
Ram: $ram
Disk(s): 
$disk_info

Network Information
-------------------
FQDN: $fqdn
Host Address: $ip_address
Gateway IP: $gateway_ip
DNS Server: $dns_server

System Status
-------------
Users Logged In: $users_logged_in
Disk Space: $disk_space
Process Count: $process_count
Load Averages: $load_averages
Listening Network Ports: $(ss -tuln | wc -l)
UFW Status: $ufw_status

EOF

echo

